# -*- coding: utf-8 -*-
"""Tak03_CS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_n4FdntZ2zHyA2bL9WzK6XMRw3U-1ST
"""

import re

def check_password_strength(password):
    score = 0
    feedback = []

    # Length Check
    if len(password) >= 8:
        score += 1
    else:
        feedback.append("❌ Password should be at least 8 characters long.")

    # Uppercase Check
    if re.search(r"[A-Z]", password):
        score += 1
    else:
        feedback.append("❌ Add at least one uppercase letter.")

    # Lowercase Check
    if re.search(r"[a-z]", password):
        score += 1
    else:
        feedback.append("❌ Add at least one lowercase letter.")

    # Digit Check
    if re.search(r"\d", password):
        score += 1
    else:
        feedback.append("❌ Add at least one number.")

    # Special Character Check
    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        score += 1
    else:
        feedback.append("❌ Add at least one special character.")

    # Strength Rating
    if score == 5:
        strength = "🟢 Very Strong"
    elif score >= 3:
        strength = "🟡 Moderate"
    else:
        strength = "🔴 Weak"

    return strength, feedback


def main():
    print("===== Password Complexity Checker =====")
    password = input("Enter your password: ")

    strength, feedback = check_password_strength(password)

    print(f"\nPassword Strength: {strength}")

    if feedback:
        print("\nSuggestions to Improve:")
        for item in feedback:
            print(item)
    else:
        print("✅ Your password meets all security criteria!")


if __name__ == "__main__":
    main()